notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/phpunit-bin

language:
  - php
  - node_js

install:
  - composer install
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"

jobs:
  include:
    - stage: test
      php: "7.1"
      env: WP_VERSION=5.0
    - php: "7.1"
      env: WP_VERSION=latest DEV_LIB_SKIP=composer,phpcs
    - php: "7.1"
      env: WP_VERSION=4.9    DEV_LIB_SKIP=composer,phpcs
    - php: "7.2"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
    - php: "7.2"
      env: WP_VERSION=4.9    DEV_LIB_SKIP=phpcs
    - php: "7.3"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
    - php: "7.3"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
